### ISSUE TITLE
Can't figure out how to use.

### ISSUE THREAD

**Issue by CoderReece** [hiili/WindowsTorch#3]
Usually in ubuntu i just use "th train.lua -input_h5 voice.h5 -input_json voice.json -num_layers 3 -rnn_size 680 -wordvec_size 110 -gpu -1"

but that doesn't work in this windows i get this
"stdin:2: '=' expected near 'h'"

**Comment by hiili** [comment]
Once you have run the setpaths.cmd script (see README.md) and while still in the Windows command prompt, you can either:
  - Start Lua with the command `luajit`, then invoke scripts from there
  - Start Lua scripts directly from the Windows command prompt: `luajit scriptfile.lua arg1 arg2`

I hope this helps!

**Comment by CoderReece** [comment]
Many thanks i figured out how to use it. Is it possible to install custom modules for example cjson?
This is the project i was hoping to get working https://github.com/jcjohnson/torch-rnn/

**Comment by hiili** [comment]
You can install Lua rocks using the luarocks tool via the Windows command
prompt once you have set the paths. It works on Windows in the same way as
on Linux, so you can follow any Torch tutorial here. You need to have git in your
path, though, if I remember correctly (been a while since I used this the last time).

If you install rocks that need compiling, then you also have to have a
compiler installed on your computer, eg, Visual Studio (community edition
is enough), and cmake. Then you run luarocks via the Visual Studio command prompt. See
https://github.com/torch/torch7/wiki/Windows#prerequisites and
https://github.com/torch/torch7/wiki/Windows#other-packages for usage.

Also, be prepared for the fact that many packages that need compiling will
fail on Windows with compilation errors.

Edit: Mention git and cmake

**Comment by vonboettichert** [comment]
Hi,

Thank you for your work! Do you know how it is possible to 'set the path' after running the setpaths.cmd command? My lua directory contains several subfolders which need to be referenced, but running the luajit command doesn't discover all the subdirectories.
![2017-11-24 13_49_27-select administrator_ command prompt](https://user-images.githubusercontent.com/18748484/33209231-97197700-d11d-11e7-900d-7e3329fe56f3.png)


Kind regards,
Thorsten

**Comment by hiili** [comment]
Hi @vonboettichert 

You need to add your directories to the Lua package.path and package.cpath variables (for loading Lua files and dlls, respectively, from within Lua). One way is to just edit the setpaths.cmd file and add your paths to LUA_PATH and LUA_CPATH, then rerun it and luajit. You can check any Lua tutorial for further details; there's nothing Windows-specific here besides the path format.

Hope this helps!
